/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VenueSpecificationsRouteImport } from './routes/venue-specifications'
import { Route as VenueRentalRouteImport } from './routes/venue-rental'
import { Route as UpcomingEventsRouteImport } from './routes/upcoming-events'
import { Route as PastEventsRouteImport } from './routes/past-events'
import { Route as EventTypesRouteImport } from './routes/event-types'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const VenueSpecificationsRoute = VenueSpecificationsRouteImport.update({
  id: '/venue-specifications',
  path: '/venue-specifications',
  getParentRoute: () => rootRouteImport,
} as any)
const VenueRentalRoute = VenueRentalRouteImport.update({
  id: '/venue-rental',
  path: '/venue-rental',
  getParentRoute: () => rootRouteImport,
} as any)
const UpcomingEventsRoute = UpcomingEventsRouteImport.update({
  id: '/upcoming-events',
  path: '/upcoming-events',
  getParentRoute: () => rootRouteImport,
} as any)
const PastEventsRoute = PastEventsRouteImport.update({
  id: '/past-events',
  path: '/past-events',
  getParentRoute: () => rootRouteImport,
} as any)
const EventTypesRoute = EventTypesRouteImport.update({
  id: '/event-types',
  path: '/event-types',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/event-types': typeof EventTypesRoute
  '/past-events': typeof PastEventsRoute
  '/upcoming-events': typeof UpcomingEventsRoute
  '/venue-rental': typeof VenueRentalRoute
  '/venue-specifications': typeof VenueSpecificationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/event-types': typeof EventTypesRoute
  '/past-events': typeof PastEventsRoute
  '/upcoming-events': typeof UpcomingEventsRoute
  '/venue-rental': typeof VenueRentalRoute
  '/venue-specifications': typeof VenueSpecificationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/event-types': typeof EventTypesRoute
  '/past-events': typeof PastEventsRoute
  '/upcoming-events': typeof UpcomingEventsRoute
  '/venue-rental': typeof VenueRentalRoute
  '/venue-specifications': typeof VenueSpecificationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/event-types'
    | '/past-events'
    | '/upcoming-events'
    | '/venue-rental'
    | '/venue-specifications'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/event-types'
    | '/past-events'
    | '/upcoming-events'
    | '/venue-rental'
    | '/venue-specifications'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/event-types'
    | '/past-events'
    | '/upcoming-events'
    | '/venue-rental'
    | '/venue-specifications'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EventTypesRoute: typeof EventTypesRoute
  PastEventsRoute: typeof PastEventsRoute
  UpcomingEventsRoute: typeof UpcomingEventsRoute
  VenueRentalRoute: typeof VenueRentalRoute
  VenueSpecificationsRoute: typeof VenueSpecificationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/venue-specifications': {
      id: '/venue-specifications'
      path: '/venue-specifications'
      fullPath: '/venue-specifications'
      preLoaderRoute: typeof VenueSpecificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venue-rental': {
      id: '/venue-rental'
      path: '/venue-rental'
      fullPath: '/venue-rental'
      preLoaderRoute: typeof VenueRentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upcoming-events': {
      id: '/upcoming-events'
      path: '/upcoming-events'
      fullPath: '/upcoming-events'
      preLoaderRoute: typeof UpcomingEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/past-events': {
      id: '/past-events'
      path: '/past-events'
      fullPath: '/past-events'
      preLoaderRoute: typeof PastEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-types': {
      id: '/event-types'
      path: '/event-types'
      fullPath: '/event-types'
      preLoaderRoute: typeof EventTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EventTypesRoute: EventTypesRoute,
  PastEventsRoute: PastEventsRoute,
  UpcomingEventsRoute: UpcomingEventsRoute,
  VenueRentalRoute: VenueRentalRoute,
  VenueSpecificationsRoute: VenueSpecificationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
